# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38781fdb84ff6ac9f778f291af1b41fbc64c6d2025731165e68fbfa33696818e462f63b3bded683dedfc5b375d8274b1a5c9e8a2937573cc1f05f5ce09fe3017

test:
  secret_key_base: 2aa353461caa12ae970844e190b3f8377dd17d9717ec0c453feb2b1852fe1232d9717413b2791b75813d7651c068d42efda67f0e1513732096a72a0922da2446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
